import { SessionProvider } from "next-auth/react"
import type { Metadata } from "next";
//import { Geist, Geist_Mono, Inter } from "next/font/google";
import Navigation from "@/components/Navigation";
import localFont from "next/font/local";

import "./globals.css";

import { CartProvider } from "@/context/CartContext"

const roboto = localFont({
  src: [
    {
      path: "./fonts/roboto/Roboto-VariableFont_wdth,wght.ttf",
      style: "normal",
    },
    {
      path: "./fonts/roboto/Roboto-Italic-VariableFont_wdth,wght.ttf",
      style: "italic",
    },
  ],
  variable: "--font-roboto",
  display: "swap", // improves loading
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const inter = Inter({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"]
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CartProvider>
          <Navigation />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
